config/routes.rb
require 'sidekiq/web'

VegastechApp::Application.routes.draw do
  admin_constraint = lambda do |request|
    if user_id = request.session['user_id']
      User.find(user_id).admin?
    end
  end

  constraints admin_constraint do
    mount Sidekiq::Web, at: '/sidekiq'
  end

  get 'sessions/create'

  resources :tags, only: [:show, :index]
  resources :events, only: :index

  resources :posts do
    resources :votes
  end

  resources :photos do
    resources :votes
    resources :comments
  end

  resources :stories do
    resources :votes
    resources :comments
  end

  resources :sessions, only: [:create, :destroy]

  match '/rss/:count', to: 'rss#index', format: 'rss'
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/sign_out', to: 'sessions#destroy'
  match '/recent', to: 'info#recent'
  match '/about', to: 'info#about'
  match '/supporters', to: 'info#users'
  match '/best_of_week/', to: 'info#best_of_week'

  root to: 'stories#index'
end

app/models/story.rb
class Story < Post
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings

  validates :twitter_id, :uniqueness => true

  # after_create :queue_reply_checker
  after_save :self_love #:promote_tweet

  attr_accessible :twitter_id, :twitter_profile_image_url, :tag_ids, :start_time

  def from_api?
    twitter_id.include?('meetup') || twitter_id.include?('ticket_cake')
  end

  def self.events_in_the_furture
    # where('start_time IS NOT NULL AND start_time > ?', Time.zone.now )
    where('start_time > ?', Time.zone.now - 45.minutes )
  end

  def self.find_or_create_by_meetup_id(json_event)
    if story = self.find_by_twitter_id("meetup_#{json_event['id']}")
      story
    else
      self.create_from_meetup(json_event)
    end
  end

  def self.find_or_create_by_ticket_cake_id(xml_event)
    if story = self.find_by_twitter_id("ticket_cake_#{xml_event['guid'].to_i}")
      story
    else
      self.create_from_ticket_cake(xml_event)
    end
  end

  def self.create_from_meetup(json_event)
    start_time_milliseconds = json_event['time'].to_i
    story = self.find_or_create_by_twitter_id(
      twitter_id: "meetup_#{json_event['id']}",
      twitter_handle: '@VegasTech_News',
      content: MeetupFetcher.meetup_story_content(json_event),
      tweeted_at: Time.current,
      from_user_name: 'Meetup API',
      start_time: Time.at(start_time_milliseconds / 1000),
      twitter_profile_image_url: 'http://vegastech.lvrug.org/assets/meetupapi_normal.png'
      )

    Tagging.create(story_id: story.id, tag_id: 1)
    
  end

  def self.create_from_ticket_cake(xml_event)
    start_time = Time.zone.parse(/content="(.*)"/.match(xml_event['pubDate'])[1]) + 1.hour
    return unless xml_event['description'].include?('#VegasTech')
    story = self.find_or_create_by_twitter_id(
      twitter_id: "ticket_cake_#{xml_event['guid']}",
      twitter_handle: '@VegasTech_News',
      content: TicketCakeFetcher.story_content(xml_event),
      tweeted_at: Time.current,
      from_user_name: 'Ticket Cake API',
      start_time: start_time,
      twitter_profile_image_url: 'http://vegastech.lvrug.org/assets/ticket_cake_thumb_normall.jpg'
      )

    Tagging.create(story_id: story.id, tag_id: 1)
    
  end


  def self.create_from_tweet(tweet)
    story = self.create(
      twitter_id: tweet.id.to_s,
      twitter_handle: "@#{tweet.user.screen_name}",
      twitter_profile_image_url: tweet.user.profile_image_url,
      content: tweet.text,
      tweeted_at: tweet.created_at,
      from_user_name: tweet.user.name)

    media = tweet.respond_to?(:media) ? tweet.media : tweet.entities[:media]
    Photo.create_from_story_and_media(story, media) unless media.blank? || media.empty?

    story
  end

  def self.find_or_create_by_tweet(tweet)
    if story = self.find_by_twitter_id(tweet.id)
      story
    else
      self.create_from_tweet(tweet)
    end
  end

  def promote_tweet
    if votes_count == 5
      Twitter.update("RT #{twitter_handle}: #{content}".truncate(140))
    end
  end

  private

  def self_love
    if id_changed?
      votes.create(twitter_handle: twitter_handle, value: 1)
    end
  end

  def queue_reply_checker
    redis = Redis.new
    redis.set(twitter_id, twitter_id)
    redis.expire(twitter_id, (24*60*60))
    ReplyChecker.perform_in(10.minutes, twitter_id, twitter_id)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :ensure_admin, only: [:edit, :update, :destroy]

  def index
    @stories = Story.within_past_month.ranked.page(params[:page]).limit(25)
  end

  def show
    @story = Story.find(params[:id])
    @comments = @story.comments.order('votes_count desc, created_at')
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])

    if @story.update_attributes(params[:story])
      redirect_to root_url, notice: 'Tags have been updated.'
    else
      render :edit
    end
  end


  def destroy
    @story = Story.find(params[:id])
    
    @story.destroy
    redirect_to root_url 
  end

private

  def ensure_admin
    if current_user.nil? || !current_user.admin?
      redirect_to root_url
    end
  end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.slim
=simple_form_for(@story, :html => { :class => 'form-horizontal' }) do |f|

  .form-inputs
    = f.association :tags, collection: Tag.order('name ASC'), :as => :check_boxes
    = f.input :start_time, :wrapper => :prepend, label: false do

      = content_tag :div, "Start Time", class: "input-append date", id: 'datetimepicker' do
        
        = content_tag :span, "Start Time", class: "add-on" do
          i data-time-icon="icon-time" data-date-icon="icon-calendar"


        = f.input_field :start_time, as: :string, 'data-format' => "dd/MM/yyyy hh:mm:ss"

  .form-actions
    = f.submit "Update", class: 'btn'

app/views/stories/_old_story.html.erb
<div class="story" data-id="<%= story.id %>" data-score="<%= story.score %>">
  <div class="row">
    <div class="content">
      <%= image_tag(asset_path('pin.png'), class: 'left-pin visible-desktop') %>
      <%= image_tag(asset_path('pin.png'), class: 'right-pin visible-desktop') %>
      <%= image_tag(asset_path('pin.png'), class: 'center-pin hidden-desktop') %>

      <div class="span7">
        <%= auto_link(story.content, url_target: '_blank').html_safe %>
        <div class="metadata">
          <a href="<%= link_from_handle(story.twitter_handle) %>" target="_blank">
            <img src="<%= story.twitter_profile_image_url %>">
          </a>
          <span class="handle"><%= link_to(story.twitter_handle, link_from_handle(story.twitter_handle), target: '_blank') %></span>
          <span class="age">
            <%= link_to("#{time_ago_in_words(story.tweeted_at)} ago".html_safe, link_from_story(story), target: 'blank') %>
          </span>
          <span class="comments">
            <%= link_to("#{story.comments.size.to_i} Comments", story_path(story)) %>
          </span>
          <% if current_user && current_user.admin? %>
            <span class="comments">
              <%= link_to("Add Tags", edit_story_path(story)) %>
            </span>
          <% end %>
        </div>
      </div>

      <div class="span2">
        <% if current_user && !current_user.voted_on?(story) %>
          <%= link_to("<i class='icon-thumbs-up icon-white'></i>".html_safe, "#retweet-modal-#{story.twitter_id}", 'data-toggle' => 'modal', class: 'vote') %>
        <% elsif current_user && current_user.voted_on?(story) %>
          <div class="vote"><%= "<i class='icon-ok icon-white'></i>".html_safe %></div>
        <% else current_user %>
          <%= link_to("<i class='icon-thumbs-up icon-white'></i>".html_safe, '/auth/twitter', class: 'vote') %>
        <% end %>

        <div class="rank"><%= "#{story.vote_count} points" %></div>
        <div class="score"><%#= "#{story.score.to_f}" %></div>

      </div>

      <br class="clear">
    </div>
  </div>
</div>
<div class="modal hide" id="retweet-modal-<%= story.twitter_id %>">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Would you like to retweet this as well?</h3>
  </div>
  <div class="modal-body">
    <div class="story">
      <div class="content">
        <%= auto_link(story.content, url_target: '_blank').html_safe %>
        <div class="metadata">
          <a href="<%= link_from_handle(story.twitter_handle) %>" target="_blank"><img src="<%= story.twitter_profile_image_url %>"></a>
          <span class="handle"><%= link_to(story.twitter_handle, link_from_handle(story.twitter_handle), target: '_blank') %></span>
          <span class="age">
            <%= link_to("#{time_ago_in_words(story.tweeted_at)} ago".html_safe, link_from_story(story), target: 'blank') %>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= link_to('Just Vote', story_votes_path(story), 'data-dismiss' => 'modal', class: 'btn', method: 'post', remote: true) %>
    <%= link_to("Vote &amp; Retweet <i class = 'icon-retweet'></i>".html_safe, story_votes_path(story, retweet: 1), 'data-dismiss' => 'modal', class: 'btn btn-inverse', method: 'post', remote: true) %>
  </div>
</div>

app/views/stories/_story.html.erb
<div class="story" data-id="<%= story.id %>" data-score="<%= story.score %>">
  <div class="row">
    <div class="content">
      <%= image_tag(asset_path('pin.png'), class: 'left-pin visible-desktop') %>
      <%= image_tag(asset_path('pin.png'), class: 'right-pin visible-desktop') %>
      <%= image_tag(asset_path('pin.png'), class: 'center-pin hidden-desktop') %>

      <div class="span7">
        <%= auto_link(story.content, url_target: '_blank').html_safe %>
        <div class="metadata">
          <a href="<%= link_from_handle(story.twitter_handle) %>" target="_blank">
            <img src="<%= story.twitter_profile_image_url %>">
          </a>
          <span class="handle"><%= link_to(story.twitter_handle, link_from_handle(story.twitter_handle), target: '_blank') %></span>
          <span class="age">
            <%= link_to("#{time_ago_in_words(story.tweeted_at)} ago".html_safe, link_from_story(story), target: 'blank') %>
          </span>
          <span class="comments">
            <%= link_to("#{story.comments.size.to_i} Comments", story_path(story)) %>
          </span>
          <% if current_user && current_user.admin? %>
            <span class="comments">
              <%= link_to("Add Tags", edit_story_path(story)) %>
            </span>
          <% end %>
        </div>
      </div>

      <div class="span2">
        <% if current_user && !current_user.voted_on?(story) %>
          <%= link_to("<i class='icon-thumbs-up icon-white'></i>".html_safe, "#retweet-modal-#{story.twitter_id}", 'data-toggle' => 'modal', class: 'vote') %>
        <% elsif current_user && current_user.voted_on?(story) %>
          <div class="vote"><%= "<i class='icon-ok icon-white'></i>".html_safe %></div>
        <% else current_user %>
          <%= link_to("<i class='icon-thumbs-up icon-white'></i>".html_safe, '/auth/twitter', class: 'vote') %>
        <% end %>

        <div class="rank"><%= "#{story.vote_count} points" %></div>
        <div class="score"><%#= "#{story.score.to_f}" %></div>

      </div>

      <br class="clear">
    </div>
  </div>
</div>
<div class="modal hide" id="retweet-modal-<%= story.twitter_id %>">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Would you like to retweet this as well?</h3>
  </div>
  <div class="modal-body">
    <div class="story">
      <div class="content">
        <%= auto_link(story.content, url_target: '_blank').html_safe %>
        <div class="metadata">
          <a href="<%= link_from_handle(story.twitter_handle) %>" target="_blank"><img src="<%= story.twitter_profile_image_url %>"></a>
          <span class="handle"><%= link_to(story.twitter_handle, link_from_handle(story.twitter_handle), target: '_blank') %></span>
          <span class="age">
            <%= link_to("#{time_ago_in_words(story.tweeted_at)} ago".html_safe, link_from_story(story), target: 'blank') %>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= link_to('Just Vote', story_votes_path(story), 'data-dismiss' => 'modal', class: 'btn', method: 'post', remote: true) %>
    <%= link_to("Vote &amp; Retweet <i class = 'icon-retweet'></i>".html_safe, story_votes_path(story, retweet: 1), 'data-dismiss' => 'modal', class: 'btn btn-inverse', method: 'post', remote: true) %>
  </div>
</div>

app/views/stories/_story.html.slim
.story data-id="#{story.id}" data-score="#{story.score}"
  .row-fluid
    .content
      / = image_tag(asset_path('pin.png'), class: 'left-pin visible-desktop') 
      / = image_tag(asset_path('pin.png'), class: 'right-pin visible-desktop') 
      / = image_tag(asset_path('pin.png'), class: 'center-pin hidden-desktop') 

      .span9
        .tweet-words
          = auto_link(story.content, url_target: '_blank').html_safe 
        
        .tag-icons.pull-right
          - story.tags.each do |tag|
            = link_to("<i class='#{tag.icon_label}'></i>".html_safe, tag, title: tag.name)
        .metadata
          - if story.from_api?
            a href="#{ link_from_api_source(story.twitter_id)}" target="_blank"
              = image_tag(story.twitter_profile_image_url)
            
            span.handle= link_to(story.from_user_name, link_from_api_source(story.twitter_id), target: '_blank')


          - else
            a href="#{ link_from_handle(story.twitter_handle)}" target="_blank"
              = image_tag(story.twitter_profile_image_url)
            
            span.handle= link_to(story.twitter_handle, link_from_handle(story.twitter_handle), target: '_blank')

          .pull-right
            span.comments
              - if story.comments.size == 0
                = link_to("Start Discussion", story_path(story))
              - else
                = link_to("#{pluralize(story.comments.size, 'Comment')}", story_path(story)) 
            
            - if current_user && current_user.admin? 
              span.comments
                = link_to("Add Tags", edit_story_path(story), class: 'btn btn-mini') 
                = link_to("Delete", story_path(story), method: :delete, confirm: 'Are you sure you want to delete this?', class: 'btn btn-danger btn-mini') 

          span.age
            - if story.from_api?
              = "#{time_ago_in_words(story.tweeted_at)} ago"
            - else
              = link_to("#{time_ago_in_words(story.tweeted_at)} ago".html_safe, link_from_story(story), target: 'blank') 
          
          .visible-phone
            .rank= pluralize( story.vote_count, 'Point')
            - if current_user && !current_user.voted_on?(story) 
              = link_to("<i class='icon-circle-arrow-up'></i>".html_safe, "#retweet-modal-#{story.twitter_id}", 'data-toggle' => 'modal', class: 'vote') 
            - elsif current_user && current_user.voted_on?(story) 
              .voted
                i.icon-circle-arrow-up
            - else current_user 
              = link_to("<i class='icon-circle-arrow-up'></i>".html_safe, '/auth/twitter', class: 'vote') 


      .hidden-phone
        .span3.vote_actions
          center
            .rank= pluralize( story.vote_count, 'Point')
            - if current_user && !current_user.voted_on?(story) 
              = link_to("<i class='icon-circle-arrow-up'></i>".html_safe, "#retweet-modal-#{story.twitter_id}", 'data-toggle' => 'modal', class: 'vote') 
            - elsif current_user && current_user.voted_on?(story) 
              .voted
                i.icon-circle-arrow-up
            - else current_user 
              = link_to("<i class='icon-circle-arrow-up'></i>".html_safe, '/auth/twitter', class: 'vote') 

          / .score #{story.score.to_f}



.modal.hide id="#{'retweet-modal-' + story.twitter_id}"
  .modal-header
    button type="button" class="close" data-dismiss="modal"
      | ×
    h3 Would you like to retweet this as well?
  
  .modal-body
    .story
      .content
        = auto_link(story.content, url_target: '_blank').html_safe 
        .metadata
          a href="#{link_from_handle(story.twitter_handle)}" target="_blank"
            = image_tag(story.twitter_profile_image_url)
          span.handle
            =link_to(story.twitter_handle, link_from_handle(story.twitter_handle), target: '_blank') 
          span.age
            = link_to("#{time_ago_in_words(story.tweeted_at)} ago".html_safe, link_from_story(story), target: 'blank') 
  
  .modal-footer
    = link_to('Just Vote', story_votes_path(story), 'data-dismiss' => 'modal', class: 'btn', method: 'post', remote: true) 
    = link_to("Vote &amp; Retweet <i class = 'icon-retweet'></i>".html_safe, story_votes_path(story, retweet: 1), 'data-dismiss' => 'modal', class: 'btn btn-inverse', method: 'post', remote: true) 
  

app/views/stories/edit.html.slim
h1 Add Tags

= render :partial => 'story', :locals => {:story => @story} 

= render :partial => 'form' 

app/views/stories/index.html.slim
=render 'shared/story_index'

app/views/stories/new.html.erb
<%- model_class = @story.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/stories/show.html.slim
= render(partial: 'stories/story', locals: {story:@story}) 

- if @comments.count > 0 
  h1 Discussion
  .comments
    - @comments.each do |comment| 
      = render(partial: 'comments/comment', locals: {story: comment}) 

- if @comments.empty? && current_user 
  h3 There are no comments for this story.
  | Start the discussion by submitting a comment below.
- elsif !@comments.empty? && current_user 
  h3 Continue the discussion by adding your thoughts.
- elsif @comments.empty? && !current_user 
  h3 There are no comments for this story.
  p Sign in to continue the discussion.
- elsif !@comments.empty? && !current_user 
  h3 Sign in to continue the discussion.

- if current_user 
  = simple_form_for([@story, @story.comments.build(post_to_twitter:true)]) do |f| 
    .row.comment-form
      .span1
        = image_tag(current_user.twitter_profile_image_url) 

      .span8
        .control-group
          .controls
            = f.input :content, input_html: { class: 'span9', rows: '13' } 
            = f.input :post_to_twitter, label: false, as: :boolean, inline_label: "Yes, reply to #{@story.twitter_handle}  on Twitter, too."


        = f.submit('Post Your Comment', class: 'btn btn-large btn-primary') 
 