config/routes.rb
require 'sidekiq/web'

VegastechApp::Application.routes.draw do
  admin_constraint = lambda do |request|
    if user_id = request.session['user_id']
      User.find(user_id).admin?
    end
  end

  constraints admin_constraint do
    mount Sidekiq::Web, at: '/sidekiq'
  end

  get 'sessions/create'

  resources :tags, only: [:show, :index]
  resources :events, only: :index

  resources :posts do
    resources :votes
  end

  resources :photos do
    resources :votes
    resources :comments
  end

  resources :stories do
    resources :votes
    resources :comments
  end

  resources :sessions, only: [:create, :destroy]

  match '/rss/:count', to: 'rss#index', format: 'rss'
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/sign_out', to: 'sessions#destroy'
  match '/recent', to: 'info#recent'
  match '/about', to: 'info#about'
  match '/supporters', to: 'info#users'
  match '/best_of_week/', to: 'info#best_of_week'

  root to: 'stories#index'
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post, counter_cache: true

  validates_uniqueness_of :twitter_handle, scope: :post_id
  validates_presence_of :twitter_handle
  validates_presence_of :post_id
  validates_presence_of :value
  validates_format_of :twitter_handle, with: /\A@\w+\Z/
  validates_inclusion_of :value, in: [-1,1]

  attr_accessible :twitter_handle, :value, :twitter_id
  attr_accessor :twitter_id

  # after_create :queue_reply_checker

  def story
    post
  end

  def comment
    post
  end

  def story=(val)
    post = val
  end

  def comment=(val)
    post = val
  end

  private

  def queue_reply_checker
    return true unless twitter_id.present?
    redis = Redis.new
    redis.set(twitter_id, post.twitter_id)
    redis.expire(twitter_id, (24*60*60))
    ReplyChecker.perform_in(10.minutes, twitter_id, post.twitter_id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @votes }
    end
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vote }
    end
  end

  # GET /votes/new
  # GET /votes/new.json
  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vote }
    end
  end

  # GET /votes/1/edit
  def edit
    @vote = Vote.find(params[:id])
  end

  # POST /votes
  # POST /votes.json
  def create
    @post = Post.find(params[:story_id])

    if params[:retweet].to_i == 1
      current_user.twitter_client.retweet(@post.twitter_id)
    end

    respond_to do |format|
      if current_user.up_vote(@post)
        @post.reload
        format.html { redirect_to(stories_path, notice: 'Vote was successfully created.') }
        format.js
      else
        @error = 'Your vote was invalid'
        flash[:error] = @error
        format.html { redirect_to(stories_path) }
        format.js
      end
    end
  end

  # PUT /votes/1
  # PUT /votes/1.json
  def update
    @vote = Vote.find(params[:id])

    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to votes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :twitter_handle %><br />
    <%= f.text_field :twitter_handle %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :story_id %><br />
    <%= f.number_field :story_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/create.js.erb
<% if @error %>
  <%# TODO %>
<% else %>
  $('.story[data-id="<%= @post.id %>"] .vote').replaceWith('<div class="voted"><i class="icon-circle-arrow-up"></i></div>')
  $('.story[data-id="<%= @post.id %>"] .rank').text('<%= @post.votes_count %> points')
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <tr>
    <th>Twitter handle</th>
    <th>Value</th>
    <th>Story</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.twitter_handle %></td>
    <td><%= vote.value %></td>
    <td><%= vote.story_id %></td>
    <td><%= link_to 'Show', vote %></td>
    <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', vote, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Twitter handle:</b>
  <%= @vote.twitter_handle %>
</p>

<p>
  <b>Value:</b>
  <%= @vote.value %>
</p>

<p>
  <b>Story:</b>
  <%= @vote.story_id %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>