config/routes.rb
require 'sidekiq/web'

VegastechApp::Application.routes.draw do
  admin_constraint = lambda do |request|
    if user_id = request.session['user_id']
      User.find(user_id).admin?
    end
  end

  constraints admin_constraint do
    mount Sidekiq::Web, at: '/sidekiq'
  end

  get 'sessions/create'

  resources :tags, only: [:show, :index]
  resources :events, only: :index

  resources :posts do
    resources :votes
  end

  resources :photos do
    resources :votes
    resources :comments
  end

  resources :stories do
    resources :votes
    resources :comments
  end

  resources :sessions, only: [:create, :destroy]

  match '/rss/:count', to: 'rss#index', format: 'rss'
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/sign_out', to: 'sessions#destroy'
  match '/recent', to: 'info#recent'
  match '/about', to: 'info#about'
  match '/supporters', to: 'info#users'
  match '/best_of_week/', to: 'info#best_of_week'

  root to: 'stories#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon-precomposed" href="/assets/apple-touch-icon-iphone.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/apple-touch-icon-ipad.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/apple-touch-icon-iphone4.png" />
    <link rel="alternate" type="application/rss+xml" title="RSS" href="<%= rss_url(5) %>" />
    <title><%= content_for?(:title) ? yield(:title) : "#VegasTech Bulletin Board" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag('application', media: 'all') %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="offset1 span10 offset1">
          <h1><%= link_to('#VegasTech Bulletin Board', root_url) %></h1>

          <div class="navbar">
            <div class="navbar-inner">
              <div class="container">
                <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </a>

                <a class="brand visible-phone" href="/">#VegasTech BB</a>

                <div class="container nav-collapse">
                  <ul class="nav">
                    <li><%= link_to "Events", tag_path('1')  %></li>
                    <li><%= link_to "Questions", tag_path('2')  %></li>
                    <li><%= link_to "Advice", tag_path('3')  %></li>
                    <li><%= link_to "Whining", tag_path('4')  %></li>
                    <!-- <li><%= link_to "Photos", photos_path  %></li> -->
                    <li><%= link_to "Recent", recent_path  %></li>
                    <li><%= link_to "Best of week", best_of_week_path  %></li>
                    <li><%= link_to "Jobs", "http://hirevegastech.com", target: 'new'  %></li>
                    <li class='dropdown visible-desktop'><%= link_to "Calendars", '#', :class => 'dropdown-toggle', "data-toggle" => "dropdown"  %>
                      <ul class = 'dropdown-menu'>
                        <li><%= link_to 'VegasTech.com Events Calendar', 'http://vegastech.com/events/', target: 'new'  %></li>
                        <li><%= link_to 'TBAN Events Calendar', 'https://www.tban.com/events/', target: 'new'  %></li>        
                        <li><%= link_to 'Work In Progress Calendar', 'http://www.workinprogress.lv/event-calendar/', target: 'new'  %></li>
                      </ul>
                    </li>
                    <li class='dropdown visible-desktop'><%= link_to "Coworking", '#', :class => 'dropdown-toggle', "data-toggle" => "dropdown"  %>
                      <ul class = 'dropdown-menu'>
                        <li><%= link_to 'CoBiz Coworking', 'http://cobizcoworking.com/', target: 'new'  %></li>
                        <li><%= link_to 'The InNEVation Center', 'http://innevation.com/', target: 'new'  %></li>
                        <li><%= link_to 'Work In Progress', 'http://workinprogress.lv/', target: 'new'  %></li>
                      </ul>
                    </li>
                    <li class='dropdown visible-desktop'><%= link_to('RSS', '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown')  %>
                      <ul class = 'dropdown-menu'>
                        <li><%= link_to('Reaching 5 Points', rss_path(5), target: 'new') %></li>
                        <li><%= link_to('Reaching 10 Points', rss_path(10), target: 'new') %></li>
                        <li><%= link_to('Reaching 20 Points', rss_path(20), target: 'new') %></li>
                      </ul>
                    </li>
                    <li class='hidden-desktop'><%= link_to 'VegasTech.com Events Calendar', 'http://vegastech.com/events/', target: 'new'  %></li>
                    <li class='hidden-desktop'><%= link_to 'Work In Progress', 'http://workinprogress.lv/events/', target: 'new'  %></li>
                    <li class='hidden-desktop'><%= link_to 'TBAN Events Calendar', 'http://www.tban.us/calendar/', target: 'new'  %></li>
                  </ul>
                  <ul class="nav pull-right">
                    <% if logged_in? %>
                      <li>
                        <%= link_to('<i class="icon-user icon-white"></i>'.html_safe + current_user.twitter_handle, '#') %>
                        <li><%= link_to "Sign out", "/sessions/destroy", method: 'delete'  %></li>
                      </li>
                    <% else %>
                      <li><%= link_to(image_tag('bird_black_16_0.png', class: 'black_bird') + "Sign in", "/auth/twitter")  %></li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="offset1 span10 offset1">
              <% unless flash[:notice].blank? %>
                <div class="alert alert-success fade in">
                  <a class="close" data-dismiss="alert" href="&times;">×</a>
                  <h3><%= flash[:notice] %> </h3>
                </div>
              <% end %>

              <% if logged_in? %>
                <div class="alert alert-info hidden-desktop">
                  <center>
                    <%= "Currently signed in as #{current_user.twitter_handle}" %>
                  </center>
                </div>
              <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span12">
          <div class="footer">
            <p class="logos">
              <%= link_to(image_tag(asset_path('lvrug_logo.png')), 'http://lvrug.org', target: '_blank') %>
            </p>
            <p>&copy; <%= Date.today.year %> - A Project by <%= link_to('The Las Vegas Ruby User Group', 'http://lvrug.org', target: '_blank') %> (<%= link_to('@LVRUG', 'http://twitter.com/lvrug', target: '_blank') %>). Hosted at the <%= link_to('Switch SuperNAP', 'http://www.switchlv.com', target: 'blank') %></p>
          </div>
        </div>
      </div>
    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag('application') %>

    <!-- Beging Google Analytics Code -->

    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-33716623-1']);
      _gaq.push(['_setDomainName', 'none']);
      _gaq.push(['_setAllowLinker', true]);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = display_meta_tags :site => "#VegasTech Bulletin Board", :reverse => true
    = stylesheet_link_tag "application", :media => "all"
 
    link rel='apple-touch-icon-precomposed' href="#{asset_path('apple-touch-icon-iphone.png')}"
    link rel='apple-touch-icon-precomposed' sizes="72x72"  href="#{asset_path('apple-touch-icon-iphone4.png') }"
    link rel='apple-touch-icon-precomposed' sizes="114x114" href="#{asset_path('apple-touch-icon-ipad.png') }"
    link rel="icon" type="image/png" href="#{asset_path('apple-touch-icon-iphone4.png') }"

    link(href='https://fonts.googleapis.com/css?family=Lato:100,200,300,400,700' rel='stylesheet' type='text/css')

    =csrf_meta_tags
    
    /[if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"

    = stylesheet_link_tag('application', media: 'all')

  body
    .container
      .row
        .span12
          center.hidden-phone
            h1= link_to('<strong>#VegasTech</strong> Bulletin Board'.html_safe, root_url)

          .navbar.navbar-fixed-top
            .navbar-inner
              .container
                a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse"
                  span class="icon-bar"
                  span class="icon-bar"
                  span class="icon-bar"

                a class="mobile-brand brand visible-phone" href="/"#VegasTech Bulletin Board

                .container.nav-collapse
                  ul.nav.pull-right
                    li= link_to "Current", root_url
                    li= link_to "Recent", recent_path  
                    li= link_to "Events", events_path 

                    li.dropdown.visible-desktop
                      = link_to "More Stuff <b class='caret'></b>".html_safe, '#', :class => 'dropdown-toggle', "data-toggle" => "dropdown"  
                      ul.dropdown-menu
                        li= link_to "Advice", tag_path('3') 
                        li= link_to "Downtown", tag_path('13') 
                        li= link_to "Introductions and Follow Ups", tag_path('11')  
                        li= link_to "Jobs", tag_path('4')  
                        li= link_to "Just For Fun", tag_path('9')  
                        li= link_to "Press", tag_path('7')
                        li= link_to "Q&A", tag_path('2')  
                        li= link_to "Startups", tag_path('6')  
                        li= link_to "Support and Encouragement", tag_path('12')
                        / li= link_to "Photos", photos_path
                        li= link_to "Visiting Town", tag_path('8')  
                        li.divider
                        li= link_to "Best of week", best_of_week_path  
                        li= link_to "Supporters", supporters_path  

                    / li.dropdown.visible-desktop
                    /   = link_to "Calendars", '#', :class => 'dropdown-toggle', "data-toggle" => "dropdown"  
                    /   ul.dropdown-menu
                    /     li= link_to 'VegasTech.com Events Calendar', 'http://vegastech.com/events/', target: 'new'  
                    /     li= link_to 'TBAN Events Calendar', 'https://www.tban.com/events/', target: 'new'          
                    /     li= link_to 'Work In Progress Calendar', 'http://www.workinprogress.lv/event-calendar/', target: 'new'  

                    li.dropdown.visible-desktop
                      = link_to "Coworking <b class='caret'></b>".html_safe, '#', :class => 'dropdown-toggle', "data-toggle" => "dropdown"  
                      ul.dropdown-menu
                        li= link_to 'CoBiz', 'http://cobizcoworking.com/', target: 'new'  
                        li= link_to 'The InNEVation Center', 'http://innevation.com/', target: 'new'  
                        li= link_to 'Work In Progress', 'http://workinprogress.lv/', target: 'new'  

                    / li.dropdown.visible-desktop
                    /   = link_to("RSS <b class='caret'></b>".html_safe, '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown')  
                    /   ul.dropdown-menu
                    /     li= link_to('Reaching 5 Points', rss_path(5), target: 'new') 
                    /     li= link_to('Reaching 10 Points', rss_path(10), target: 'new') 
                    /     li= link_to('Reaching 20 Points', rss_path(20), target: 'new') 

                    / li.hidden-desktop= link_to 'VegasTech.com Events Calendar', 'http://vegastech.com/events/', target: 'new'  
                    / li.hidden-desktop= link_to 'Work In Progress', 'http://workinprogress.lv/events/', target: 'new'  
                    / li.hidden-desktop= link_to 'TBAN Events Calendar', 'http://www.tban.us/calendar/', target: 'new'  

                    - if logged_in?

                      li.dropdown.visible-desktop
                        = link_to "<i class='icon-user icon-white'></i> Account <b class='caret'></b>".html_safe, '#', :class => 'dropdown-toggle', "data-toggle" => "dropdown" 
                        ul.dropdown-menu

                          li= link_to(current_user.twitter_handle, '#') 
                          - if current_user_is_admin?
                            li.divider
                            li= link_to "Tags Report", tags_path  

                          
                          li.divider
                          li= link_to "Sign out", "/sessions/destroy", method: 'delete'  
                    - else 
                      li= link_to("<i class='icon-twitter'></i> Sign in".html_safe, "/auth/twitter")
 
    .container
      .content
        .row
           .span12
            = bootstrap_flash

            - if logged_in? 
              .alert.alert-info.hidden-desktop
                center
                  = "Currently signed in as #{current_user.twitter_handle}" 

            = yield 

    .container-fluid
      .row
        .footer

          p &copy; 2013  - A Project by #{link_to('The Las Vegas Ruby User Group', 'http://lvrug.org', target: '_blank')} for members of the #{link_to('#VegasTech', root_url)} Community.
          p= link_to('More About This Site', about_path)

          p.logos
            = link_to(image_tag(asset_path('lvrug_logo.png')), 'http://lvrug.org', target: '_blank') 


    / Javascripts
    / ================================================== 
    / Placed at the end of the document so the pages load faster 
    = javascript_include_tag('application') 
    = render 'shared/google_analytics'

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon-precomposed" href="/assets/apple-touch-icon-iphone.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/apple-touch-icon-ipad.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/apple-touch-icon-iphone4.png" />
    <link rel="alternate" type="application/rss+xml" title="RSS" href="<%= rss_url(5) %>" />
    <title><%= content_for?(:title) ? yield(:title) : "#VegasTech Bulletin Board" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag('application', media: 'all') %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="offset1 span10 offset1">
          <center>
            <h1><%= link_to('#VegasTech Bulletin Board', root_url) %></h1>
          </center>
          <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
              <div class="container">
                <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </a>

                <a class="brand visible-phone" href="/">#VegasTech BB</a>

                <div class="container nav-collapse">
                  <ul class="nav">
                    <li><%= link_to "Current", root_url  %></li>
                    <li><%= link_to "Recent", recent_path  %></li>
                    <li><%= link_to "Events", tag_path('1')  %></li>
                    <li><%= link_to "Q&A", tag_path('2')  %></li>
                    <li><%= link_to "Advice", tag_path('3')  %></li>
                    <li><%= link_to "Whining", tag_path('4')  %></li>
                    <!-- <li><%= link_to "Photos", photos_path  %></li> -->
<!--                     <li><%= link_to "Best of week", best_of_week_path  %></li>
 -->                    <li><%= link_to "Jobs", "http://hirevegastech.com", target: 'new'  %></li>
                    <li class='dropdown visible-desktop'><%= link_to "Calendars", '#', :class => 'dropdown-toggle', "data-toggle" => "dropdown"  %>
                      <ul class = 'dropdown-menu'>
                        <li><%= link_to 'VegasTech.com Events Calendar', 'http://vegastech.com/events/', target: 'new'  %></li>
                        <li><%= link_to 'TBAN Events Calendar', 'https://www.tban.com/events/', target: 'new'  %></li>        
                        <li><%= link_to 'Work In Progress Calendar', 'http://www.workinprogress.lv/event-calendar/', target: 'new'  %></li>
                      </ul>
                    </li>
                    <li class='dropdown visible-desktop'><%= link_to "Coworking <b class='caret'></b>".html_safe, '#', :class => 'dropdown-toggle', "data-toggle" => "dropdown"  %>
                      <ul class = 'dropdown-menu'>
                        <li><%= link_to 'CoBiz Coworking', 'http://cobizcoworking.com/', target: 'new'  %></li>
                        <li><%= link_to 'The InNEVation Center', 'http://innevation.com/', target: 'new'  %></li>
                        <li><%= link_to 'Work In Progress', 'http://workinprogress.lv/', target: 'new'  %></li>
                      </ul>
                    </li>
                    <li class='dropdown visible-desktop'><%= link_to('RSS', '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown')  %>
                      <ul class = 'dropdown-menu'>
                        <li><%= link_to('Reaching 5 Points', rss_path(5), target: 'new') %></li>
                        <li><%= link_to('Reaching 10 Points', rss_path(10), target: 'new') %></li>
                        <li><%= link_to('Reaching 20 Points', rss_path(20), target: 'new') %></li>
                      </ul>
                    </li>
                    <li class='hidden-desktop'><%= link_to 'VegasTech.com Events Calendar', 'http://vegastech.com/events/', target: 'new'  %></li>
                    <li class='hidden-desktop'><%= link_to 'Work In Progress', 'http://workinprogress.lv/events/', target: 'new'  %></li>
                    <li class='hidden-desktop'><%= link_to 'TBAN Events Calendar', 'http://www.tban.us/calendar/', target: 'new'  %></li>
                  </ul>
                  <ul class="nav pull-right">
                    <% if logged_in? %>
                      <li>
                        <%= link_to('<i class="icon-user icon-white"></i>'.html_safe + current_user.twitter_handle, '#') %>
                        <li><%= link_to "Sign out", "/sessions/destroy", method: 'delete'  %></li>
                      </li>
                    <% else %>
                      <li><%= link_to(image_tag('bird_black_16_0.png', class: 'black_bird') + "Sign in", "/auth/twitter")  %></li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="offset1 span10 offset1">
              <% unless flash[:notice].blank? %>
                <div class="alert alert-success fade in">
                  <a class="close" data-dismiss="alert" href="&times;">×</a>
                  <h3><%= flash[:notice] %> </h3>
                </div>
              <% end %>

              <% if logged_in? %>
                <div class="alert alert-info hidden-desktop">
                  <center>
                    <%= "Currently signed in as #{current_user.twitter_handle}" %>
                  </center>
                </div>
              <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span12">
          <div class="footer">
            <p class="logos">
              <%= link_to(image_tag(asset_path('lvrug_logo.png')), 'http://lvrug.org', target: '_blank') %>
            </p>
            <p>&copy; <%= Date.today.year %> - A Project by <%= link_to('The Las Vegas Ruby User Group', 'http://lvrug.org', target: '_blank') %> (<%= link_to('@LVRUG', 'http://twitter.com/lvrug', target: '_blank') %>). Hosted at the <%= link_to('Switch SuperNAP', 'http://www.switchlv.com', target: 'blank') %></p>
          </div>
        </div>
      </div>
    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag('application') %>

    <!-- Beging Google Analytics Code -->

    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-33716623-1']);
      _gaq.push(['_setDomainName', 'none']);
      _gaq.push(['_setAllowLinker', true]);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </body>
</html>